FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    clang-format-17 \
    && ln -s /usr/bin/clang-format-17 /usr/local/bin/clang-format \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /src
ENTRYPOINT ["clang-format"]
