macro(enable_doxygen)
  find_package(Doxygen)
  if(DOXYGEN_FOUND)
    set(DOXYGEN_CALLER_GRAPH YES)
    set(DOXYGEN_CALL_GRAPH YES)
    set(DOXYGEN_EXTRACT_ALL YES)
    doxygen_add_docs(doxygen ${PROJECT_SOURCE_DIR})
  else()
    message(WARNING "Doxygen not found, documentation not available")
  endif()
endmacro()
